name: iOS KMP Build
description: Builds iOS app (optionally with KMP framework) and uploads to TestFlight

inputs:
  # Required
  match_password:
    description: "Password for decrypting of certificates and provisioning profiles."
    required: true
  app_store_connect_api_key_key:
    description: "Private App Store Connect API key for submitting build to App Store."
    required: true
  app_store_connect_api_key_key_id:
    required: true
    description: "Private App Store Connect API key for submitting build to App Store."
  app_store_connect_api_key_issuer_id:
    required: true
    description: "Private App Store Connect API issuer key for submitting build to App Store."
  # Optional
  secret_xcconfig_path:
    description: "Path to the .xcconfig file. Selected secret properties will be appended to the end of this file."
    required: false
  secret_properties:
    required: false
    description: "Secrets in the format KEY = VALUE (one per line)."
  secret_required_keys:
    description: "Comma-separated list of required secret keys."
    required: false
  kmp_swift_package_integration:
    description: "Whether KMP is integrated in Xcode project as a Swift Package"
    required: false
  kmp_swift_package_path:
    description: "If `kmp_swift_package_integration` is 'true', then specifies a location of local Swift Package with Makefile. Example: 'iosApp/shared/KMP`"
    required: false
  kmp_swift_package_flavor:
    description: "If `kmp_swift_package_integration`, specifies build flavor of KMP Package"
    required: false
  custom_values:
    description: "Custom string that can contains values specified in your workflow file. Those values will be placed into environment variable. Example: \"CUSTOM-1: 1; CUSTOM-2: 2\""
    required: false
  testflight_changelog:
    required: false
    description: "Will be used as TestFlight changelog"

runs:
  using: "composite"
  steps:
    - name: Export secrets to .xcconfig file
      if: ${{ inputs.secret_xcconfig_path != '' }}
      uses: futuredapp/.github/.github/actions/ios-export-secrets@main
      with:
        XCCONFIG_PATH: ${{ inputs.secret_xcconfig_path }}
        SECRET_PROPERTIES: ${{ inputs.secret_properties }}
        REQUIRED_KEYS: ${{ inputs.secret_required_keys }}
    - name: Build KMP Package
      if: ${{ inputs.kmp_swift_package_integration }}
      env:
        KMP_BUILD_FLAVOR: ${{ inputs.kmp_swift_package_flavor }}
        KMP_FRAMEWORK_BUILD_TYPE: release
      shell: bash
      run: |
        cd ${{ inputs.kmp_swift_package_path }}
        make build
    - name: Fastlane Beta
      working-directory: iosApp
      shell: bash
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec fastlane beta
      env:
        MATCH_PASSWORD: ${{ inputs.match_password }}
        PR_TITLE: ${{ inputs.testflight_changelog }}
        APP_STORE_CONNECT_API_KEY_KEY: ${{ inputs.app_store_connect_api_key_key }}
        APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ inputs.app_store_connect_api_key_key_id }}
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ inputs.app_store_connect_api_key_issuer_id }}
        CUSTOM_VALUES: ${{ inputs.custom_values }}
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: Build.ipa
        path: build_output/*.ipa
    - name: Upload dSYM
      uses: actions/upload-artifact@v4
      with:
        name: Build.app.dSYM.zip
        path: build_output/*.app.dSYM.zip
