name: 'Fastlane Beta'
description: 'Runs Fastlane beta'
inputs:
  match_password:
    description: 'Match password'
    required: true
  testflight_changelog:
    description: 'Testflight changelog'
    required: false
  app_store_connect_api_key_key:
    description: 'App Store Connect API Key'
    required: true
  app_store_connect_api_key_key_id:
    description: 'App Store Connect API Key ID'
    required: true
  app_store_connect_api_key_issuer_id:
    description: 'App Store Connect API Key Issuer ID'
    required: true
  build_number:
    description: 'Custom build number. Skips auto-increment from TestFlight.'
    required: false
  version_number:
    description: 'Custom version number. Overrides default.'
    required: false
  custom_values:
    description: 'Custom values'
    required: false
  ios_root_path:
    description: 'Path to iOS project root directory containing Gemfile. If not specified, uses current directory.'
    required: false
  custom_build_path:
    description: 'Path to directory containing Fastfile. If not specified, uses ios_root_path or current directory.'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Run beta script
      shell: bash
      run: ${{ github.action_path }}/beta.sh
      env:
        MATCH_PASSWORD: ${{ inputs.match_password }}
        PR_TITLE: ${{ inputs.testflight_changelog }}
        APP_STORE_CONNECT_API_KEY_KEY: ${{ inputs.app_store_connect_api_key_key }}
        APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ inputs.app_store_connect_api_key_key_id }}
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ inputs.app_store_connect_api_key_issuer_id }}
        BUILD_NUMBER: ${{ inputs.build_number }}
        VERSION_NUMBER: ${{ inputs.version_number }}
        CUSTOM_VALUES: ${{ inputs.custom_values }}
        IOS_ROOT_PATH: ${{ inputs.ios_root_path }}
        CUSTOM_BUILD_PATH: ${{ inputs.custom_build_path }}