name: 'Fastlane Test'
description: 'Runs Fastlane test'
inputs:
  github_token:
    description: 'GitHub token'
    required: false
  custom_values:
    description: 'Custom values'
    required: false
  ios_root_path:
    description: 'Path to iOS project root directory containing Gemfile. If not specified, uses current directory.'
    required: false
  custom_build_path:
    description: 'Path to directory containing Fastfile. If not specified, uses ios_root_path or current directory.'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Run test script
      shell: bash
      run: ${{ github.action_path }}/test.sh
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        CUSTOM_VALUES: ${{ inputs.custom_values }}
        IOS_ROOT_PATH: ${{ inputs.ios_root_path }}
        CUSTOM_BUILD_PATH: ${{ inputs.custom_build_path }}
