name: Export secret properties to iOS .xcconfig file.
description: Encodes secret values to Base64 and writes them into the specified .xcconfig file in KEY = VALUE format.

inputs:
  XCCONFIG_PATH:
    description: Path to the .xcconfig file. Selected secret properties will be appended to the end of this file.
    required: true
  SECRET_PROPERTIES:
    description: Secrets in the format KEY = VALUE (one per line).
    required: false
  REQUIRED_KEYS:
    description: Comma-separated list of required keys.
    required: false

runs:
  using: "composite"
  steps:
    - name: Run script
      shell: sh
      working-directory: ${{ github.action_path }}
      run: ./entrypoint.sh
      env:
        XCCONFIG_PATH: ${{ inputs.XCCONFIG_PATH }}
        SECRET_PROPERTIES: ${{ inputs.SECRET_PROPERTIES }}
        REQUIRED_KEYS: ${{ inputs.REQUIRED_KEYS }}