name: Detect changes and generate changelog
description: Detects changes since the last built commit and generates a changelog.

inputs:
  checkout_depth:
    required: false
    description: 'The depth of the git history to fetch. Default is 100.'
    type: number
    default: 100
  debug:
    required: false
    description: 'Enable debug mode. Default is false.'
    type: boolean
    default: false
  fallback_lookback:
    required: false
    description: 'The amount of time to look back for merge commits when no previous build commit is found (e.g., "24 hours", "7 days", "2 weeks"). Default is "24 hours".'
    default: "24 hours"
  cache_key_prefix:
    required: false
    description: 'Custom prefix for cache keys. If not provided, will use latest_builded_commit-. If provided, format will be {prefix}-latest_builded_commit-'
  use_git_lfs:
    required: false
    description: 'Whether to download Git-LFS files during checkout. Default is false.'
    type: boolean
    default: false
  target_branch:
    required: false
    description: 'Target branch name(s) to detect merges into. Regex pattern used to filter which merges are included in the changelog. Default captures merges into main, develop, or master branches.'
    default: "(main|develop|master)"

outputs:
  skip_build:
    description: 'Indicates if the build should be skipped'
    value: ${{ steps.determine_skip.outputs.skip }}
  changelog:
    description: 'The generated changelog formatted as a string'
    value: ${{ steps.generate_changelog.outputs.changelog_string }}
  merged_branches:
    description: 'List of merged branch names'
    value: ${{ steps.generate_changelog.outputs.merged_branches }}
  cache_key:
    description: 'Cache key to store latest built commit for this branch'
    value: ${{ steps.cache_keys.outputs.cache_key_prefix }}-${{ github.sha }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.checkout_depth }}
        lfs: ${{ inputs.use_git_lfs }}

    - name: Calculate cache keys
      id: cache_keys
      shell: bash
      run: ${{ github.action_path }}/cache-keys.sh
      env:
        CACHE_KEY_PREFIX: ${{ inputs.cache_key_prefix }}
        DEBUG: ${{ inputs.debug }}

    - name: Restore cache for previous build commit SHA
      id: restore_last_build_cache
      uses: actions/cache/restore@v4
      continue-on-error: true
      with:
        path: latest_builded_commit.txt
        key: ${{ steps.cache_keys.outputs.cache_key_prefix }}-${{ github.sha }}
        restore-keys: |
          ${{ steps.cache_keys.outputs.cache_key_prefix }}-

    - name: Determine commit range for changelog and skip build
      id: determine_range
      shell: bash
      run: ${{ github.action_path }}/determine-range.sh
      env:
        DEBUG: ${{ inputs.debug }}
        FALLBACK_LOOKBACK: ${{ inputs.fallback_lookback }}

    - name: Set skip_build output
      id: determine_skip
      shell: bash
      run: |
        # Set composite action output based on previous step's result.
        echo "skip=${{ steps.determine_range.outputs.build_should_skip }}" >> $GITHUB_OUTPUT

    - name: Generate changelog
      id: generate_changelog
      shell: bash
      # Only run if build is NOT skipped and a valid from_commit exists.
      if: steps.determine_skip.outputs.skip == 'false' && steps.determine_range.outputs.from_commit != ''
      run: ${{ github.action_path }}/generate-changelog.sh
      env:
        FROM_COMMIT: ${{ steps.determine_range.outputs.from_commit }}
        TO_COMMIT: ${{ steps.determine_range.outputs.to_commit }}
        DEBUG: ${{ inputs.debug }}
        TARGET_BRANCH: ${{ inputs.target_branch }}
