name: 'Fastlane Release'
description: 'Runs Fastlane release'
inputs:
  match_password:
    description: 'Match password'
    required: true
  version_number:
    description: 'Version number (supports x.y.z or x.y.z-k format where k is build number)'
    required: false
  build_number:
    description: 'Custom build number. Skips auto-increment from TestFlight.'
    required: false
  app_store_connect_api_key_key:
    description: 'App Store Connect API Key'
    required: true
  app_store_connect_api_key_key_id:
    description: 'App Store Connect API Key ID'
    required: true
  app_store_connect_api_key_issuer_id:
    description: 'App Store Connect API Key Issuer ID'
    required: true
  custom_values:
    description: 'Custom values'
    required: false
  ios_root_path:
    description: 'Path to iOS project root directory containing Gemfile. If not specified, uses current directory.'
    required: false
  custom_build_path:
    description: 'Path to directory containing Fastfile. If not specified, uses ios_root_path or current directory.'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Parse version tag
      id: parse_version
      shell: bash
      run: ${{ github.action_path }}/parse-version-tag.sh
      env:
        VERSION_TAG: ${{ inputs.version_number }}
    - name: Run release script
      shell: bash
      run: ${{ github.action_path }}/release.sh
      env:
        MATCH_PASSWORD: ${{ inputs.match_password }}
        VERSION_NUMBER: ${{ steps.parse_version.outputs.version_number }}
        BUILD_NUMBER: ${{ inputs.build_number || steps.parse_version.outputs.build_number }}
        APP_STORE_CONNECT_API_KEY_KEY: ${{ inputs.app_store_connect_api_key_key }}
        APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ inputs.app_store_connect_api_key_key_id }}
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ inputs.app_store_connect_api_key_issuer_id }}
        CUSTOM_VALUES: ${{ inputs.custom_values }}
        IOS_ROOT_PATH: ${{ inputs.ios_root_path }}
        CUSTOM_BUILD_PATH: ${{ inputs.custom_build_path }}
