name: 'Fastlane Release'
description: 'Runs Fastlane release'
inputs:
  match_password:
    description: 'Match password'
    required: true
  version_number:
    description: 'Version number'
    required: false
  app_store_connect_api_key_key:
    description: 'App Store Connect API Key'
    required: true
  app_store_connect_api_key_key_id:
    description: 'App Store Connect API Key ID'
    required: true
  app_store_connect_api_key_issuer_id:
    description: 'App Store Connect API Key Issuer ID'
    required: true
  custom_values:
    description: 'Custom values'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Run release script
      shell: bash
      run: ${{ github.action_path }}/release.sh
      env:
        MATCH_PASSWORD: ${{ inputs.match_password }}
        VERSION_NUMBER: ${{ inputs.version_number }}
        APP_STORE_CONNECT_API_KEY_KEY: ${{ inputs.app_store_connect_api_key_key }}
        APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ inputs.app_store_connect_api_key_key_id }}
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ inputs.app_store_connect_api_key_issuer_id }}
        CUSTOM_VALUES: ${{ inputs.custom_values }}
