name: Android Google Play Release

on:
  workflow_call:
    inputs:
      ## Required Inputs
      TASK_NAME:
        description: "A Gradle task(s) for executing baseline profiles `generateBaselineProfile`"
        required: true
        type: string

      ## Optional Inputs
      USE_GIT_LFS:
        description: "Whether to download Git-LFS files"
        type: boolean
        required: false
        default: false
      SECRET_PROPERTIES_FILE:
        description: "A path to file that will be populated with contents of 'SECRET_PROPERTIES' secret. This file can be picked up by Secrets Gradle plugin to embed secrets into BuildConfig."
        required: false
        type: string
        default: secrets.properties
      TIMEOUT_MINUTES:
        description: "Job timeout in minutes"
        required: false
        type: number
        default: 60

    secrets:
      SIGNING_KEYSTORE_PASSWORD:
        description: "Password to provided keystore"
        required: true
      SIGNING_KEY_ALIAS:
        description: "Alias of the signing key in the provided keystore"
        required: true
      SIGNING_KEY_PASSWORD:
        description: "Password to the key in the provided keystore"
        required: true
      SECRET_PROPERTIES:
        required: false
        description: "Custom string that contains key-value properties as secrets. Contents of this secret will be placed into file specified by 'SECRET_PROPERTIES_FILE' input."

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Generate Baseline Profiles
    runs-on: [ ubuntu-latest ]
    timeout-minutes: ${{ inputs.TIMEOUT_MINUTES }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: ${{ inputs.USE_GIT_LFS }}
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: false
      - name: Prepare Environment
        run: |
          echo '${{ secrets.SECRET_PROPERTIES }}' > ${{ inputs.SECRET_PROPERTIES_FILE }}
      - name: Setup GMD
        run: ./gradlew ${{ inputs.TASK_NAME }}
          -Pandroid.experimental.testOptions.managedDevices.emulator.showKernelLogging=true
          -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'Generate baseline profiles'
          branch: 'feature/generate-baseline-profiles'
          title: 'Generate baseline profiles'
          body: ''
