name: Android Release to Google Play

on:
  workflow_call:
    inputs:
      ## Required Inputs
      VERSION_NAME:
        description: "Build version name"
        required: true
        type: string
      BUNDLE_GRADLE_TASK:
        description: "A Gradle task for assembling app bundle, for example `bundleRelease`"
        required: true
        type: string
      SIGNING_KEYSTORE_PATH:
        description: "Path to keystore for signing of universal APK. Example: `keystore/debug.jks' or 'androidApp/signing/debug.keystore'"
        required: true
        type: string
      GOOGLE_PLAY_APPLICATION_ID:
        description: "Google Play applicationId"
        required: true
        type: string
      GOOGLE_PLAY_WHATSNEW_DIRECTORY:
        description: "Path to directory with changelog files according to documentation in https://github.com/r0adkll/upload-google-play"
        required: true
        type: string

      ## Optional Inputs
      USE_GIT_LFS:
        description: "Whether to download Git-LFS files"
        type: boolean
        required: false
        default: false
      BUILD_NUMBER_OFFSET:
        description: "Build number offset. This number will be added to GITHUB_RUN_NUMBER and can be used to make corrections to build numbers."
        required: false
        type: number
        default: 0
      KMP_FLAVOR:
        description: "KMP Build flavor. This is optional and only required by KMP projects and can be ignored on pure Android projects"
        required: false
        type: string
        default: 'prod'
      SECRET_PROPERTIES_FILE:
        description: "A path to file that fill be populated with contents of 'SECRET_PROPERTIES' secret. This file can be picked up by Secrets Gradle plugin to embed secrets into BuildConfig."
        required: false
        type: string
        default: secrets.properties
      CHANGES_NOT_SENT_FOR_REVIEW:
        description: 'A changesNotSentForReview Google Play flag. Enable when last google review failed, disable when last review was successful.'
        type: boolean
        required: false
        default: false
      TIMEOUT_MINUTES:
        description: "Job timeout in minutes"
        required: false
        type: number
        default: 30
      JAVA_VERSION:
        description: "Java version to use"
        required: false
        type: string
        default: '17'
      JAVA_DISTRIBUTION:
        description: "Java distribution to use"
        required: false
        type: string
        default: 'zulu'
      GRADLE_OPTS:
        description: "Gradle options"
        required: false
        type: string
        default: ""

    secrets:
      SIGNING_KEYSTORE_PASSWORD:
        description: "Password to provided keystore"
        required: true
      SIGNING_KEY_ALIAS:
        description: "Alias of the signing key in the provided keystore"
        required: true
      SIGNING_KEY_PASSWORD:
        description: "Password to the key in the provided keystore"
        required: true
      GOOGLE_PLAY_PUBLISH_SERVICE_ACCOUNT:
        required: true
        description: "JSON key of service account with permissions to upload build to Google Play"
      SECRET_PROPERTIES:
        required: false
        description: "Custom string that contains key-value properties as secrets. Contents of this secret will be placed into file specified by 'SECRET_PROPERTIES_FILE' input."

jobs:
  build:
    name: Release Build
    runs-on: [ ubuntu-latest ]
    timeout-minutes: ${{ inputs.TIMEOUT_MINUTES }}
    env:
      GRADLE_OPTS: ${{ inputs.GRADLE_OPTS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: ${{ inputs.USE_GIT_LFS }}
      - name: Set up environment
        # TODO update branch ref to main, reject pull request if you see this
        uses: futuredapp/.github/.github/actions/android-setup-environment@feature/matsem/changelog-android
        with:
          java_version: ${{ inputs.JAVA_VERSION }}
          java_distribution: ${{ inputs.JAVA_DISTRIBUTION }}
      - name: Build and release
        # TODO update branch ref to main, reject pull request if you see this
        uses: futuredapp/.github/.github/actions/android-build-googlePlay@feature/matsem/changelog-android
        with:
          bundle_gradle_task: ${{ inputs.BUNDLE_GRADLE_TASK }}
          version_name: ${{ inputs.VERSION_NAME }}
          signing_keystore_password: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          signing_key_alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          signing_key_password: ${{ secrets.SIGNING_KEY_PASSWORD }}
          google_play_application_id: ${{ inputs.GOOGLE_PLAY_APPLICATION_ID }}
          google_play_whatsnew_dir: ${{ inputs.GOOGLE_PLAY_WHATSNEW_DIRECTORY }}
          google_play_publish_service_account: ${{ secrets.GOOGLE_PLAY_PUBLISH_SERVICE_ACCOUNT }}
          changes_not_sent_for_review: ${{ inputs.CHANGES_NOT_SENT_FOR_REVIEW }}
          build_number_offset: ${{ inputs.BUILD_NUMBER_OFFSET }}
          kmp_flavor: ${{ inputs.KMP_FLAVOR }}
          secret_properties_file: ${{ inputs.SECRET_PROPERTIES_FILE }}
          secret_properties: ${{ secrets.SECRET_PROPERTIES }}
