name: Cloud Release

on:
  workflow_call:
    secrets:
      # Key for accessing repo with Apple certificates
      # and provisioning profiles and repo with imported
      # Fastlane lanes.
      SSH_PRIVATE_KEY:
        required: true
      MATCH_PASSWORD:
        required: true
      APP_STORE_CONNECT_API_KEY_KEY:
        required: true
jobs:
  release:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Fastlane Beta
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec fastlane beta
      env:
        APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: Build.ipa
        path: build_output/*.ipa
    - name: Upload dSYM
      uses: actions/upload-artifact@v2
      with:
        name: Build.app.dSYM.zip
        path: build_output/*.app.dSYM.zip
