name: Cleanup

on:
  workflow_dispatch:
    inputs:
      derived_data:
        description: 'Clear derived data'
        required: false 
        type: boolean
      simulator:
        description: 'Clear simulator content'
        required: false 
        type: boolean

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
    - name: Bundle intall
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Bundle intall
      if: $DERIVED_DATA == true
      run: |
        bundle exec fastlane run clear_derived_data
    - name: Bundle intall
      if: $SIMULATOR == true
      run: |
        bundle exec fastlane run reset_simulator_contents
