name: Cloud Test

on:
  workflow_call:
    inputs:
      use_git_lfs:
        description: Whether to download Git-LFS files.
        type: boolean
        required: false
      custom_values:
        description: "Custom string that can contains values specified in your workflow file. Those values will be placed into environment variable. Example: \"CUSTOM-1: 1; CUSTOM-2: 2\""
        type: string
        required: false
    secrets:
      SSH_PRIVATE_KEY:
        required: true
        description: >
          Key for accessing repo with Apple certificates
          and provisioning profiles and repo with imported
          Fastlane lanes.

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: ${{ inputs.use_git_lfs }}
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
    - name: Fastlane Test
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec fastlane test
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_VALUES: ${{ inputs.custom_values }}
