name: Cloud Build

on:
  workflow_call:
    inputs:
      use_git_lfs:
        description: Whether to download Git-LFS files.
        type: boolean
        required: false
      custom_values:
        description: "Custom string that can contains values specified in your workflow file. Those values will be placed into environment variable. Example: \"CUSTOM-1: 1; CUSTOM-2: 2\""
        type: string
        required: false
      xcconfig_path:
        description: Path to the .xcconfig file. Selected secret properties will be appended to the end of this file.
        type: string
        required: false
        default: ""
      required_keys:
        description: Comma-separated list of required keys.
        type: string
        required: false
        default: ""
    secrets:
      SSH_PRIVATE_KEY:
        required: true
        description: >
          Key for accessing repo with Apple certificates
          and provisioning profiles and repo with imported
          Fastlane lanes.
      MATCH_PASSWORD:
        required: true
        description: >
          Password for decrypting of certificates and provisioning profiles.
      APP_STORE_CONNECT_API_KEY_KEY:
        required: true
        description: >
          Private App Store Connect API key for submitting build to App Store.
      APP_STORE_CONNECT_API_KEY_KEY_ID:
        required: true
        description: >
          Private App Store Connect API key for submitting build to App Store.
      APP_STORE_CONNECT_API_KEY_ISSUER_ID:
        required: true
        description: >
          Private App Store Connect API issuer key for submitting build to App Store.
      SECRET_PROPERTIES:
        required: false
        description: >
         Secrets in the format KEY = VALUE (one per line).

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: ${{ inputs.use_git_lfs }}
    - name: Export secrets to .xcconfig file
      if: ${{ inputs.xcconfig_path != '' && inputs.required_keys != '' }}
      uses: futuredapp/.github/.github/actions/export_secrets_ios@feature/iOS-secrets-injection
      with:
        XCCONFIG_PATH: ${{ inputs.xcconfig_path }}
        SECRET_PROPERTIES: ${{ secrets.SECRET_PROPERTIES }}
        REQUIRED_KEYS: ${{ inputs.required_keys }}
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
    - name: Fastlane Beta
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec fastlane beta
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
        APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
        CUSTOM_VALUES: ${{ inputs.custom_values }}
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: Build.ipa
        path: build_output/*.ipa
    - name: Upload dSYM
      uses: actions/upload-artifact@v4
      with:
        name: Build.app.dSYM.zip
        path: build_output/*.app.dSYM.zip
