name: Cloud Build

on:
  workflow_call:
    inputs:
      use_git_lfs:
        description: Whether to download Git-LFS files.
        type: boolean
        required: false
    secrets:
      SSH_PRIVATE_KEY:
        required: true
        description: >
          Key for accessing repo with Apple certificates
          and provisioning profiles and repo with imported
          Fastlane lanes.
      MATCH_PASSWORD:
        required: true
        description: >
          Password for decrypting of certificates and provisioning profiles.
      APP_STORE_CONNECT_API_KEY_KEY:
        required: true
        description: >
          Private App Store Connect API key for submitting build to App Store.
      APP_STORE_CONNECT_API_KEY_KEY_ID:
        required: true
        description: >
          Private App Store Connect API key for submitting build to App Store.
      APP_STORE_CONNECT_API_KEY_ISSUER_ID:
        required: true
        description: >
          Private App Store Connect API issuer key for submitting build to App Store.

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: ${{ inputs.use_git_lfs }}
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Fastlane Beta
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec fastlane beta
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
        APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: Build.ipa
        path: build_output/*.ipa
    - name: Upload dSYM
      uses: actions/upload-artifact@v2
      with:
        name: Build.app.dSYM.zip
        path: build_output/*.app.dSYM.zip
