name: Cloud Build

on:
  workflow_call:
    inputs:
      use_git_lfs:
        description: Whether to download Git-LFS files.
        type: boolean
        required: false
    secrets:
      SSH_PRIVATE_KEY:
        required: true
        description: >
          Key for accessing repo with Apple certificates
          and provisioning profiles and repo with imported
          Fastlane lanes.
      MATCH_PASSWORD:
        required: true
        description: >
          Password for decrypting of certificates and provisioning profiles.
      APPCENTER_API_TOKEN:
        required: true
        description: Token for submitting builds to App Center.

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: ${{ inputs.use_git_lfs }}
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Fastlane Enterprise
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec fastlane enterprise
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: Build.ipa
        path: build_output/*.ipa
    - name: Upload dSYM
      uses: actions/upload-artifact@v2
      with:
        name: Build.app.dSYM.zip
        path: build_output/*.app.dSYM.zip
