name: Cloud Test

on:
  workflow_call:
    secrets:
      # Key for accessing repo with Apple certificates
      # and provisioning profiles and repo with imported
      # Fastlane lanes.
      SSH_PRIVATE_KEY:
        required: true
jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Cache Ruby gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Fastlane Test
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec fastlane test
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
