name: Detect Changes

# This workflow is a central decision point in the KMP project CI/CD pipeline that determines
# which platform-specific workflows should run based on changed files.
#
# This workflow serves as a wrapper around the reusable kmp-detect-changes action 
# (.github/actions/kmp-detect-changes) to provide a callable workflow interface.
#
# The following project structure is assumed: Android app in `androidApp/` path and iOS app in `iosApp/` path
# relative to the repository root.
#
# It produces two outputs:
# - `iosFiles`: Will be set to 'true' if any files affecting iOS build were changed
# - `androidFiles`: Will be set to `true` if any files affecting Android build were changed
#
# Usage:
#   1. Call this workflow first in your trigger workflows
#   2. Use the outputs to conditionally run platform-specific workflows
#
# Example:
#   jobs:
#     changes:
#       uses: ./.github/workflows/kmp-cloud-detect-changes.yml
#     ios-build:
#       needs: changes
#       if: ${{ needs.changes.outputs.iosFiles == 'true' }}
#       uses: ./.github/workflows/build_ios.yml
#
# Note: For direct action usage in other workflows, you can also use:
#   - name: Detect Changes
#     uses: futuredapp/.github/.github/actions/kmp-detect-changes@main

on:
  workflow_call:
    inputs:
      USE_GIT_LFS:
        description: "Whether to download Git-LFS files"
        type: boolean
        required: false
        default: false
    outputs:
      iosFiles:
        description: "Whether files affecting iOS build changed (all files except those in androidApp/)"
        value: ${{ jobs.detect-changes.outputs.iosFiles }}
      androidFiles:
        description: "Whether files affecting Android build changed (all files except those in iosApp/)"
        value: ${{ jobs.detect-changes.outputs.androidFiles }}

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      # Matches all files which can affect iOS build if changed
      iosFiles: ${{ steps.detect.outputs.iosFiles }}
      # Matches all files which can affect Android build if changed
      androidFiles: ${{ steps.detect.outputs.androidFiles }}
    steps:
      - name: Detect Changes
        id: detect
        # TODO update branch ref to main, reject pull request if you see this
        uses: futuredapp/.github/.github/actions/kmp-detect-changes@feature/android-refactor
        with:
          USE_GIT_LFS: ${{ inputs.USE_GIT_LFS }}
